---
- name: Install Apache 2 Web Server  
  hosts: production,test  
  tasks:    
    - name: install apache2 
      apt: 
        name: apache2
        state: latest
        update_cache: yes
    - name: start apache2
      service:
        name: apache2
        state: started
    - name: enable apache2
      service:
        name: apache2
        enabled: yes
- name: install PHP 7.4
  hosts: production,test
  tasks:
    - name: Installation install software-properties-common
      apt: name=software-properties-common

    - name: "Repo PHP 7.4"
      apt_repository:
        repo="ppa:ondrej/php"

    - name: "Updating the repo"
      apt: update_cache=yes

    - name: Installation PHP 7.4
      apt: name=php7.4 state=present

    - name: install lamp stack
      apt:
        pkg:
          - php7.4-mysql
          - php7.4-curl
          - php7.4-json
          - php7.4-cgi
          - php7.4-xsl
          - php7.4-cgi
          - php7.4-gd
          - php7.4-mbstring
          - php7.4-zip
          - php7.4-xmlrpc
          - php7.4-soap
          - php7.4-intl
          - libapache2-mod-php
        state: present
        update_cache: yes
